<<<<<<< HEAD
// This file was generated by Prisma, and assumes you have installed the following:
// npm install --save-dev prisma dotenv
import "dotenv/config";
import { defineConfig } from "prisma/config";
=======
import { defineConfig, env } from "prisma/config";
import * as dotenv from 'dotenv';

dotenv.config();
>>>>>>> d97dff57472c7b688f24cd0eecce2bf733fdccfe

export default defineConfig({
  schema: "prisma/schema.prisma",
  migrations: {
    path: "prisma/migrations",
  },
<<<<<<< HEAD
  datasource: {
    url: process.env["DATABASE_URL"],
=======
  engine: "classic",
  datasource: {
    url: env("DATABASE_URL"),
>>>>>>> d97dff57472c7b688f24cd0eecce2bf733fdccfe
  },
});
